#server
server:
    port: 80
    servlet:      context-path: /
    tomcat:
      threads:
        max: 500
        min-spare: 5  
#HikariCp
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: tarena
  thymeleaf: #thymeleaf
    prefix:   classpath:/templates/pages/
    suffix: .html
    cache: false #kai-fa-shi-yong
  aop:    proxy-target-class: false    #jdk Proxy(优先使用jdk,但目标类没有实现接口就会使用cglib代理)
  task:
    execution:      pool:        core-size: 5
        max-size: 128
        queue-capacity: 128
        keep-alive: 60000
      thread-name-prefix: DD-SEVICE-THREAD-
#spring mybatis
mybatis:
     mapper-locations:
     -  classpath:/mapper/*/*.xml

#Spring log
logging:
  level:
   com.cy: DEBUG


shiro:
  loginUrl: /doLoginUI
  web:
    enabled: true
  sessionManager:
    sessionIdCookieEnabled: true
    sessionIdUrlRewritingEnabled: false


